name: CI - Serenity BDD Login Tests with Edge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Microsoft Edge
        run: |
          sudo apt update
          sudo apt install -y microsoft-edge-stable

      - name: Install Edge WebDriver
        run: |
          EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}')
          wget -q "https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip"
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/
          rm edgedriver_linux64.zip

      - name: Give execute permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run tests with Gradle
        run: ./gradlew clean test aggregate

      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v4
        with:
          name: serenity-reports
          path: target/site/serenity
